networks:
  default: localnet
  localnet:
    url: "http://127.0.0.1:4000/api"
    chain_type: localnet
  studionet:
    url: "https://studio.genlayer.com/api"
    chain_type: studionet
  testnet_bradbury:
    chain_type: testnet_bradbury

paths:
  contracts: contracts
  artifacts: artifacts

environment: .env
