#!/usr/bin/env node
/**
 * Interactive terminal setup for the Ethereum NFT copy bot.
 * Works on macOS, Linux, and Windows (PowerShell / cmd / Terminal).
 *
 * Usage: npm run setup
 */
import fs from "node:fs";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(root, ".env");
const examplePath = path.join(root, ".env.example");

function parseEnvFile(text) {
  const values = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

function escapeEnvValue(value) {
  if (/[\s#"']/.test(value)) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

function writeEnv(values) {
  const lines = [
    "# Generated by: npm run setup",
    "# Edit this file anytime, or run npm run setup again.",
    "",
    "# Telegram — create a bot with @BotFather, then get your chat id via @userinfobot",
    `TELEGRAM_BOT_TOKEN=${escapeEnvValue(values.TELEGRAM_BOT_TOKEN || "")}`,
    `TELEGRAM_ALLOWED_CHAT_IDS=${escapeEnvValue(values.TELEGRAM_ALLOWED_CHAT_IDS || "")}`,
    "",
    "# Ethereum RPC (Alchemy recommended: https://www.alchemy.com)",
    `ETH_RPC_URL=${escapeEnvValue(values.ETH_RPC_URL || "")}`,
    `ALCHEMY_API_KEY=${escapeEnvValue(values.ALCHEMY_API_KEY || "")}`,
    "",
    "# Copy trading (keep dry-run on until you understand the risks)",
    `COPY_ENABLED=${escapeEnvValue(values.COPY_ENABLED || "false")}`,
    `DRY_RUN=${escapeEnvValue(values.DRY_RUN || "true")}`,
    `PRIVATE_KEY=${escapeEnvValue(values.PRIVATE_KEY || "")}`,
    `MAX_BUY_ETH=${escapeEnvValue(values.MAX_BUY_ETH || "0.05")}`,
    `MAX_GAS_GWEI=${escapeEnvValue(values.MAX_GAS_GWEI || "40")}`,
    `POLL_INTERVAL_MS=${escapeEnvValue(values.POLL_INTERVAL_MS || "12000")}`,
    `LOOKBACK_BLOCKS=${escapeEnvValue(values.LOOKBACK_BLOCKS || "8")}`,
    "",
    "# Optional: only copy these collections (comma-separated). Empty = any.",
    `ALLOWED_COLLECTIONS=${escapeEnvValue(values.ALLOWED_COLLECTIONS || "")}`,
    "",
    "# Optional: OpenSea API key for listing lookups when copying",
    `OPENSEA_API_KEY=${escapeEnvValue(values.OPENSEA_API_KEY || "")}`,
    "",
  ];
  fs.writeFileSync(envPath, lines.join("\n"), "utf8");
}

async function ask(rl, label, { defaultValue = "", required = false, secret = false } = {}) {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  const prompt = `${label}${suffix}: `;
  while (true) {
    const answer = (await rl.question(prompt)).trim();
    const value = answer || defaultValue;
    if (required && !value) {
      console.log("  Required — please enter a value.");
      continue;
    }
    if (secret && value) {
      console.log("  Saved (hidden).");
    }
    return value;
  }
}

async function main() {
  console.log("");
  console.log("=== Ethereum NFT Copy Bot — terminal setup ===");
  console.log(`Project folder: ${root}`);
  console.log("This writes a local .env file used when you run the bot.");
  console.log("");

  if (!fs.existsSync(examplePath)) {
    console.error("Missing .env.example — are you in the project root?");
    process.exit(1);
  }

  const existing = fs.existsSync(envPath)
    ? parseEnvFile(fs.readFileSync(envPath, "utf8"))
    : parseEnvFile(fs.readFileSync(examplePath, "utf8"));

  if (fs.existsSync(envPath)) {
    console.log("Found existing .env — pressing Enter keeps the current value.");
    console.log("");
  }

  const rl = readline.createInterface({ input, output });

  try {
    console.log("1) Telegram");
    console.log("   Message @BotFather → /newbot → copy the token");
    console.log("   Message your bot, then get your chat id from @userinfobot");
    console.log("");
    const TELEGRAM_BOT_TOKEN = await ask(rl, "TELEGRAM_BOT_TOKEN", {
      defaultValue: existing.TELEGRAM_BOT_TOKEN || "",
      required: true,
      secret: true,
    });
    const TELEGRAM_ALLOWED_CHAT_IDS = await ask(rl, "TELEGRAM_ALLOWED_CHAT_IDS", {
      defaultValue: existing.TELEGRAM_ALLOWED_CHAT_IDS || "",
      required: true,
    });

    console.log("");
    console.log("2) Ethereum RPC");
    console.log("   Alchemy dashboard → create app → copy HTTPS URL");
    console.log("");
    let ETH_RPC_URL = await ask(rl, "ETH_RPC_URL", {
      defaultValue:
        existing.ETH_RPC_URL && !existing.ETH_RPC_URL.includes("YOUR_KEY")
          ? existing.ETH_RPC_URL
          : "",
      required: true,
    });
    if (!/^https?:\/\//i.test(ETH_RPC_URL)) {
      console.log("  Tip: URL should start with https:// — keeping what you entered.");
    }

    let ALCHEMY_API_KEY = existing.ALCHEMY_API_KEY || "";
    const alchemyMatch = ETH_RPC_URL.match(/alchemy\.com\/v2\/([^/?#]+)/i);
    if (alchemyMatch && !ALCHEMY_API_KEY) {
      ALCHEMY_API_KEY = alchemyMatch[1];
      console.log("  Detected Alchemy key from RPC URL for NFT metadata.");
    } else {
      ALCHEMY_API_KEY = await ask(rl, "ALCHEMY_API_KEY (optional)", {
        defaultValue: ALCHEMY_API_KEY,
      });
    }

    console.log("");
    console.log("3) Safety defaults (recommended for first run)");
    const DRY_RUN = await ask(rl, "DRY_RUN (true/false)", {
      defaultValue: existing.DRY_RUN || "true",
    });
    const COPY_ENABLED = await ask(rl, "COPY_ENABLED (true/false)", {
      defaultValue: existing.COPY_ENABLED || "false",
    });
    const MAX_BUY_ETH = await ask(rl, "MAX_BUY_ETH", {
      defaultValue: existing.MAX_BUY_ETH || "0.05",
    });

    console.log("");
    const wantKey = (
      await ask(rl, "Set PRIVATE_KEY now? (y/N)", { defaultValue: "n" })
    ).toLowerCase();
    let PRIVATE_KEY = existing.PRIVATE_KEY || "";
    if (wantKey === "y" || wantKey === "yes") {
      PRIVATE_KEY = await ask(rl, "PRIVATE_KEY", {
        defaultValue: PRIVATE_KEY,
        secret: true,
      });
    }

    writeEnv({
      ...existing,
      TELEGRAM_BOT_TOKEN,
      TELEGRAM_ALLOWED_CHAT_IDS,
      ETH_RPC_URL,
      ALCHEMY_API_KEY,
      DRY_RUN,
      COPY_ENABLED,
      MAX_BUY_ETH,
      PRIVATE_KEY,
    });

    console.log("");
    console.log(`Wrote ${envPath}`);
    console.log("");
    console.log("Next steps in this same terminal:");
    console.log("  npm install");
    console.log("  npm run start:dev");
    console.log("");
    console.log("Or in one shot:");
    console.log("  npm run bot");
    console.log("");
    console.log("Keep that terminal open while the bot runs.");
    console.log("Then in Telegram: /start  →  /track 0xWallet Label  →  /status");
    console.log("");
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
