#!/usr/bin/env node
/**
 * Interactive terminal setup for the Binance Futures AI Trading Assistant.
 * Usage: npm run setup
 */
import fs from "node:fs";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(root, ".env");

function parseEnvFile(text) {
  const values = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

function escapeEnvValue(value) {
  if (/[\s#"']/.test(value)) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

function writeEnv(values) {
  const lines = [
    "# Generated by: npm run setup",
    "# Edit this file anytime, or run npm run setup again.",
    "",
    "# Telegram — create a bot with @BotFather, then get your chat id via @userinfobot",
    `TELEGRAM_BOT_TOKEN=${escapeEnvValue(values.TELEGRAM_BOT_TOKEN || "")}`,
    `TELEGRAM_ALLOWED_CHAT_IDS=${escapeEnvValue(values.TELEGRAM_ALLOWED_CHAT_IDS || "")}`,
    "",
    "# Exchange: mexc (recommended if Binance is blocked) or binance",
    `EXCHANGE=${escapeEnvValue(values.EXCHANGE || "mexc")}`,
    `MEXC_FUTURES_BASE_URL=${escapeEnvValue(values.MEXC_FUTURES_BASE_URL || "https://contract.mexc.com")}`,
    "",
    "# Binance Futures (only used when EXCHANGE=binance)",
    `BINANCE_API_KEY=${escapeEnvValue(values.BINANCE_API_KEY || "")}`,
    `BINANCE_API_SECRET=${escapeEnvValue(values.BINANCE_API_SECRET || "")}`,
    `BINANCE_FUTURES_BASE_URL=${escapeEnvValue(values.BINANCE_FUTURES_BASE_URL || "https://fapi.binance.com")}`,
    "",
    "# Scanner",
    `TIMEFRAME=${escapeEnvValue(values.TIMEFRAME || "15m")}`,
    `SCAN_INTERVAL_MS=${escapeEnvValue(values.SCAN_INTERVAL_MS || "60000")}`,
    `MIN_QUOTE_VOLUME_USDT=${escapeEnvValue(values.MIN_QUOTE_VOLUME_USDT || "5000000")}`,
    `MAX_PAIRS=${escapeEnvValue(values.MAX_PAIRS || "0")}`,
    `SYMBOL_WHITELIST=${escapeEnvValue(values.SYMBOL_WHITELIST || "")}`,
    `SYMBOL_BLACKLIST=${escapeEnvValue(values.SYMBOL_BLACKLIST || "")}`,
    "",
    "# EMA crossover",
    `EMA_FAST=${escapeEnvValue(values.EMA_FAST || "9")}`,
    `EMA_SLOW=${escapeEnvValue(values.EMA_SLOW || "21")}`,
    "",
    "# Technical confirmations",
    `REQUIRE_RSI=${escapeEnvValue(values.REQUIRE_RSI || "true")}`,
    `RSI_PERIOD=${escapeEnvValue(values.RSI_PERIOD || "14")}`,
    `RSI_LONG_MIN=${escapeEnvValue(values.RSI_LONG_MIN || "45")}`,
    `RSI_LONG_MAX=${escapeEnvValue(values.RSI_LONG_MAX || "70")}`,
    `RSI_SHORT_MIN=${escapeEnvValue(values.RSI_SHORT_MIN || "30")}`,
    `RSI_SHORT_MAX=${escapeEnvValue(values.RSI_SHORT_MAX || "55")}`,
    `REQUIRE_MACD=${escapeEnvValue(values.REQUIRE_MACD || "true")}`,
    `REQUIRE_VOLUME=${escapeEnvValue(values.REQUIRE_VOLUME || "true")}`,
    `VOLUME_MA_PERIOD=${escapeEnvValue(values.VOLUME_MA_PERIOD || "20")}`,
    `VOLUME_SPIKE_MULT=${escapeEnvValue(values.VOLUME_SPIKE_MULT || "1.2")}`,
    `MIN_TECHNICAL_SCORE=${escapeEnvValue(values.MIN_TECHNICAL_SCORE || "2")}`,
    "",
    "# Fundamental confirmations",
    `REQUIRE_FUNDING=${escapeEnvValue(values.REQUIRE_FUNDING || "true")}`,
    `FUNDING_LONG_MAX=${escapeEnvValue(values.FUNDING_LONG_MAX || "0.0005")}`,
    `FUNDING_SHORT_MIN=${escapeEnvValue(values.FUNDING_SHORT_MIN || "-0.0005")}`,
    `REQUIRE_OPEN_INTEREST=${escapeEnvValue(values.REQUIRE_OPEN_INTEREST || "true")}`,
    `OI_LOOKBACK_PERIODS=${escapeEnvValue(values.OI_LOOKBACK_PERIODS || "6")}`,
    `MIN_FUNDAMENTAL_SCORE=${escapeEnvValue(values.MIN_FUNDAMENTAL_SCORE || "1")}`,
    "",
    "# Risk / TP & SL (ATR-based)",
    `ATR_PERIOD=${escapeEnvValue(values.ATR_PERIOD || "14")}`,
    `STOP_LOSS_ATR_MULT=${escapeEnvValue(values.STOP_LOSS_ATR_MULT || "1.5")}`,
    `TAKE_PROFIT_ATR_MULT=${escapeEnvValue(values.TAKE_PROFIT_ATR_MULT || "3")}`,
    `TAKE_PROFIT_2_ATR_MULT=${escapeEnvValue(values.TAKE_PROFIT_2_ATR_MULT || "5")}`,
    "",
    "# Alert hygiene",
    `SIGNAL_COOLDOWN_MS=${escapeEnvValue(values.SIGNAL_COOLDOWN_MS || "3600000")}`,
    `DRY_RUN=${escapeEnvValue(values.DRY_RUN || "false")}`,
    `ALERTS_ENABLED=${escapeEnvValue(values.ALERTS_ENABLED || "true")}`,
    "",
  ];
  fs.writeFileSync(envPath, lines.join("\n"), "utf8");
}

async function ask(rl, label, { defaultValue = "", required = false } = {}) {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  const prompt = `${label}${suffix}: `;
  while (true) {
    const answer = (await rl.question(prompt)).trim();
    const value = answer || defaultValue;
    if (required && !value) {
      console.log("  Required — please enter a value.");
      continue;
    }
    return value;
  }
}

async function main() {
  console.log("");
  console.log("=== Binance Futures AI Trading Assistant — setup ===");
  console.log(`Project folder: ${root}`);
  console.log("This writes a local .env file used when you run the bot.");
  console.log("");

  const existing = fs.existsSync(envPath)
    ? parseEnvFile(fs.readFileSync(envPath, "utf8"))
    : {};

  const rl = readline.createInterface({ input, output });
  try {
    console.log("1) Telegram");
    console.log("   Message @BotFather → /newbot → copy token");
    console.log("   Message @userinfobot → copy your chat id");
    console.log("");

    const TELEGRAM_BOT_TOKEN = await ask(rl, "TELEGRAM_BOT_TOKEN", {
      defaultValue: existing.TELEGRAM_BOT_TOKEN || "",
      required: true,
    });
    const TELEGRAM_ALLOWED_CHAT_IDS = await ask(
      rl,
      "TELEGRAM_ALLOWED_CHAT_IDS",
      {
        defaultValue: existing.TELEGRAM_ALLOWED_CHAT_IDS || "",
        required: true,
      }
    );

    console.log("");
    console.log("2) Exchange + scanner (press Enter to keep)");
    const EXCHANGE = await ask(rl, "EXCHANGE (mexc or binance)", {
      defaultValue: existing.EXCHANGE || "mexc",
    });
    const TIMEFRAME = await ask(rl, "TIMEFRAME", {
      defaultValue: existing.TIMEFRAME || "15m",
    });
    const EMA_FAST = await ask(rl, "EMA_FAST", {
      defaultValue: existing.EMA_FAST || "9",
    });
    const EMA_SLOW = await ask(rl, "EMA_SLOW", {
      defaultValue: existing.EMA_SLOW || "21",
    });
    const MIN_QUOTE_VOLUME_USDT = await ask(rl, "MIN_QUOTE_VOLUME_USDT", {
      defaultValue: existing.MIN_QUOTE_VOLUME_USDT || "5000000",
    });
    const DRY_RUN = await ask(rl, "DRY_RUN (true = log only, no Telegram)", {
      defaultValue: existing.DRY_RUN || "false",
    });

    writeEnv({
      ...existing,
      TELEGRAM_BOT_TOKEN,
      TELEGRAM_ALLOWED_CHAT_IDS,
      EXCHANGE,
      TIMEFRAME,
      EMA_FAST,
      EMA_SLOW,
      MIN_QUOTE_VOLUME_USDT,
      DRY_RUN,
    });

    console.log("");
    console.log(`✓ Wrote ${envPath}`);
    console.log("Next:");
    console.log("  npm run check");
    console.log("  npm run bot");
    console.log("");
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
